version: '3'

services:
  cats:
    container_name: cats-service
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    environment:
      'DB_HOST': '172.18.0.1'
      'RABBIT_HOST': '172.18.0.1'
